=== Joshinator4/1o-DAM/Archivos Visual Studios/Lenguaje de marcas/Tema 4/Comunidad de Vecinos/Vecinos.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="comunidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" name="vecino">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigoVecino" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellidos" type="xs:string" />
                            <xs:element name="CuentaCorriente" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[0-9]{20}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>    
                            <xs:element name="cargo" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="presidente" />
                                        <xs:enumeration value="vicepresidente" />
                                        <xs:enumeration value="secretario" />
                                        <xs:enumeration value="secretaria" />
                                        <xs:enumeration value="vocal" />
                                        <xs:enumeration value="ninguno" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>    
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Joshinator4/1o-DAM/Lenguaje de marcas/Tema 4/Comunidad de Vecinos/Vecinos.xml
<?xml version="1.0" encoding="UTF-8"?>
<comunidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vecinos.xsd">
    <vecino>
        <codigoVecino>1</codigoVecino>
        <nombre>Antonio</nombre>
        <apellidos>perez</apellidos>
        <CuentaCorriente>00112233445566778899</CuentaCorriente>
        <cargo>presidente</cargo>
    </vecino>

   <vecino>
        <codigoVecino>2</codigoVecino>
        <nombre>Juan</nombre>
        <apellidos>gonzalez</apellidos>
        <CuentaCorriente>22334455667788990011</CuentaCorriente>
        <cargo>secretaria</cargo>
    </vecino>

    <vecino>
        <codigoVecino>3</codigoVecino>mv fichero1.txt
        <nombre>Manuel</nombre>
        <apellidos>SÃ¡nchez</apellidos>
        <CuentaCorriente>55226633441177889900</CuentaCorriente>
        <cargo>vocal</cargo>
    </vecino>
</comunidad>
