<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Actor [
<!ELEMENT Actor (aname+, hollywood)>
<!ELEMENT aname (fname, lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT hollywood (#PCDATA)>
<!ENTITY UofT SYSTEM "fil.xml">
]>

<Actor>
    <aname>
        <fname>Robert</fname>
        <lname>De Niro</lname>
    </aname>
    <aname>
        <fname>Al</fname>
        <lname>Paccino</lname>
    </aname>
    &UofT;
</Actor>
