=== Joshinator4/1o-DAM/Lenguaje de marcas/Tema 4/Ejercicio XSL/XSLlibro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="autor" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength  value="100"/>
                                        <xs:minLength  value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio" type="xs:decimal" />
                            <xs:element name="nPag" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:float">
                                        <xs:maxInclusive  value="1500"/>
                                        <xs:minInclusive  value="10"/>
                                    </xs:restriction>
                                </xs:simpleType> 
                            </xs:element>   
                            <xs:element name="ISBN" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>   
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Joshinator4/1o-DAM/Archivos Visual Studios/Lenguaje de marcas/Tema 4/Ejercicio XSL/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSLlibro.xsd">
    <libro>
        <titulo>El Mozárabe</titulo>
        <autor>Jesús Sánchez Adalid</autor>
        <precio>27.55</precio>
        <nPag>1336</nPag>
        <ISBN>9857-422-4751</ISBN>
    </libro>

    <libro>
        <titulo>La Sombra del Viento</titulo>
        <autor>Carlos Ruiz Zafón</autor>
        <precio>29.35</precio>
        <nPag>1436</nPag>
        <ISBN>9857-422-4741</ISBN>
    </libro>
</libros>
