=== Joshinator4/1o-DAM/Lenguaje de marcas/Tema 4/Pizzeria XML/DTDpizzeria.dtd
<!ELEMENT pizzas (pizza*)>
<!ELEMENT pizza (ingrediente+, masa, horneado, salsas*)>
<!ELEMENT ingrediente EMPTY>
<!ELEMENT masa (#PCDATA)>
<!ELEMENT horneado (#PCDATA)>
<!ELEMENT salsas (#PCDATA)>
<!ATTLIST pizza nombre CDATA #REQUIRED>
<!ATTLIST pizza precio CDATA #REQUIRED>
<!ATTLIST ingrediente nombre CDATA #REQUIRED>

=== Joshinator4/1o-DAM/Lenguaje de marcas/Tema 4/Pizzeria XML/Pizzeria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pizzas SYSTEM "DTDpizzeria.dtd">
<pizzas>
  <pizza nombre="Barbacoa" precio="8">
    <ingrediente nombre="Salsa Barbacoa"/>
    <ingrediente nombre="Mozzarella"/>
    <ingrediente nombre="Pollo"/>
    <ingrediente nombre="Bacon"/>
    <ingrediente nombre="Ternera"/>
    <masa>clasica</masa>
    <horneado>15 min</horneado>
    <salsas>barbacoa</salsas>
  </pizza>
  <pizza nombre="Margarita" precio="6">
    <ingrediente nombre="Tomate"/>
    <ingrediente nombre="JamÃ³n"/>
    <ingrediente nombre="Queso"/>
    <masa>fina</masa>
    <horneado>25 min</horneado>
  </pizza>
</pizzas>
