=== Joshinator4/1o-DAM/Lenguaje de marcas/Tema 4/Examen Tema4/ejercicio3.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name='parking'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="vehiculo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tipo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="coche" />
                                        <xs:enumeration value="moto" />
                                        <xs:enumeration value="patinete" />
                                        <xs:enumeration value="furgo" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="1" name="Matricula">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{3}[0-9]{4}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NombreCliente" type="xs:string" />
                            <xs:element name="Socio" type="xs:boolean" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Joshinator4/1o-DAM/Lenguaje de marcas/Tema 4/Examen Tema4/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<parking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio3.xsd">
    <vehiculo>
        <Tipo>moto</Tipo>
        <Matricula>DTR4487</Matricula>
        <NombreCliente>Joshua</NombreCliente>
        <Socio>false</Socio>
    </vehiculo>
    <vehiculo>
        <Tipo>coche</Tipo>
        <Matricula>ART5789</Matricula>
        <NombreCliente>Adolfo</NombreCliente>
        <Socio>true</Socio>
    </vehiculo>
</parking>
